version: "3.4"
services:
  appsmith:
    container_name: appsmith
    image: index.docker.io/appsmith/appsmith-ee
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./stacks:/appsmith-stacks
    restart: unless-stopped
